### ISSUE TITLE
Issues with Magic Castle 9.0 (on AWS)

### ISSUE THREAD

**Issue by ocaisa** [ComputeCanada/magic_castle#123]
While trying out Magic Castle 9.0 (which is great BTW), I ran into a few issues:
- Trying to base things on a CentOS 8 image (`ami-032025b3afcbb6b34`) did not work: there was never a functioning NFS or SLURM (and no users) available after 2 hours. I was curious to know how to go about debugging this? Is there more required that just updating the image?
- The JupyterHub connection has optional views such as `Desktop`, `RStudio` and `VSCode` which don't seem to work

Apart from that, I was curious if there have been any testing done on ARM?

**Comment by cmd-ntrf** [comment]
1. CentOS 8 support is currently broken because FreeIPA install is broken in CentOS 8 ([an issue related to OpenJDK]https://bugzilla.redhat.com/show_bug.cgi?id=1892216)). MC heavily depends on FreeIPA (DNS and LDAP). I am following the evolution closely and will produce a new release if required.

To debug, you can look at the puppet log in journalctl on the different node: `sudo journalctl -u puppet`. On the node named `puppet` (which is also `mgmt1` but this hostname won't work until FreeIPA is correctly installed), you should find that `ipa-server-install` is failing in the puppet log.

2. For JupyterHub, you are right. There was an update on Compute Canada CVMFS and the name of the modules required for these software to work have changed. I need to update the hieradata.

3. Testing on ARM: some but nothing extensive. I have compiled Slurm RPMs with ARM64 here :
https://copr.fedorainfracloud.org/coprs/cmdntrf/Slurm19/. There is probably some other packages that are x86 only for now that would fail during the install in Magic Castle, but it would be fairly easy to iron out. The main issue is that CC CVMFS stack does not currently support ARM, therefore limiting the out-of-the-box usage for MC. 

However, it has been [recently proposed](https://github.com/ComputeCanada/puppet-magic_castle/issues/76) to include EESSI stack in Magic Castle. If ARM supports is provided in EESSI stack, there would not be much left to do have full ARM support in MC.

**Comment by cmd-ntrf** [comment]
2. After a quick investigation, for me, VS Code and Desktop works, but not RStudio. RStudio modules parameter in puppet-jupyterhub need some fixing as I said. For VS Code and Desktop, try to refresh the page. Some it takes longer to load the software from CVMFS on the first try than the allocated timeout of jupyter-server-proxy.

**Comment by ocaisa** [comment]
Ok, I'll try it again later. Thanks for all the info!
