### ISSUE TITLE
Issue creating symlinks in NFS on CentOS8

### ISSUE THREAD

**Issue by ocaisa** [ComputeCanada/magic_castle#138]
I was testing out CentOS8 and I tried to install some software into the NFS mounts. The installation process creates symlinks and these were failing. Doing manual symlinks also failed with "Permission denied".

**Comment by cmd-ntrf** [comment]
Was the installation done as root from the login node?

**Comment by ocaisa** [comment]
No as a user in a (group readable) directory under `/project`

**Comment by ocaisa** [comment]
I've since killed the cluster, because I was really testing something else, I just wanted to log the experience here. I note that this works fine on CentOS 7.

**Comment by cmd-ntrf** [comment]
I have seen this in CentOS 7 and it was a SELinux flag that was missing. I will search the commit history for the fix.

**Comment by cmd-ntrf** [comment]
The issue happens following the deactivation of the security label export.

SELinux confined users are not authorized to create symlink on NFS. `/scratch` and `/project` are tagged as `home_t` on `mgmt1`, but since the NFS kernel bug the security labels are no longer exported.

However, CentOS 7 NFS kernel bug has been fixed, which mean I can reactivate security labels and fix this issue.

**Comment by cmd-ntrf** [comment]
I have reactivated the exportation of nfs security labels. It should now be fixed, but I still have to test.

**Comment by cmd-ntrf** [comment]
It required a bit more work, but this is now fixed properly.
