### ISSUE TITLE
Warning: Empty provider configuration blocks are not required

### ISSUE THREAD

**Issue by consideRatio** [ComputeCanada/magic_castle#168]
Using magic_castle `11.0` in the AWS release and running `terraform init` using google dns, I got the following warning that kept showing in `terraform apply` etc.

```
│ Warning: Empty provider configuration blocks are not required
│ 
│   on dns/gcloud/main.tf line 1:
│    1: provider "google" {
│ 
│ Remove the google provider block from module.dns.
```

Could it be that we should remove that, and perhaps also empty provider blocks like `provider "<name>" { }`? If so, I've found them in five places in total across this repo.

https://github.com/ComputeCanada/magic_castle/blob/aaec453e9883d6a1a3c4a1cb5e7bbba26dc4ddfc/dns/cloudflare/main.tf#L1-L2

https://github.com/ComputeCanada/magic_castle/blob/aaec453e9883d6a1a3c4a1cb5e7bbba26dc4ddfc/dns/gcloud/main.tf#L1-L2

https://github.com/ComputeCanada/magic_castle/blob/aaec453e9883d6a1a3c4a1cb5e7bbba26dc4ddfc/openstack/infrastructure.tf#L1-L2

https://github.com/ComputeCanada/magic_castle/blame/main/docs/design.md#L181

https://github.com/ComputeCanada/magic_castle/blame/main/docs/design.md#L289

**Comment by cmd-ntrf** [comment]
You are right. Apparently, empty providers were not required for a long time, but Terraform only started warning about their presence since release 0.15.0.

I have removed the empty providers you identified in the Terraform files and added a precision in the design documentation. We now mention the provider needs to be define if it requires some input parameters, like the region.

This is fixed by commit 41f0bc9feff0fde16db0cbe8967ad17657cfd1ff.

Thanks!
