### ISSUE TITLE
Heterogeneous microarchitecture cluster

### ISSUE THREAD

**Issue by ocaisa** [ComputeCanada/magic_castle#202]
Right now you can only provide a single image to Magic Castle so there is no way to support multiple microarchitectures in the same cluster. I think probably the image is the only thing that would really stop you doing this...but perhaps it also has an impact on Puppet? I guess you would also need to tag them somehow in Slurm so they can be easily used.

Not sure how interesting this would be but it is supported by [CitC](https://cluster-in-the-cloud.readthedocs.io/en/latest/).

**Comment by ocaisa** [comment]
This also might be interesting if you wanted to use different images on for nodes with different capabilities. For example, on Azure it looks like you probably want to use the HPC images on nodes that have the relevant hardware (I have seen that having things like IB configured on nodes that don't have the hardware can confuse UCX for example).

Of course, the other option would be to install the IB support, like is done for EFA on AWS.

**Comment by cmd-ntrf** [comment]
Most of puppet code is agnostic to the cpu architecture. There might be some yum repos with hardcoded x86-64, but that's an easy fix as long as there is a repo corresponding to the architecture.

The question left is how to assign a different image to different instance types, and ideally without adding too much complexity. That actually used to be possible with MC < 11. In MC 10, a user could add an `image` key to the node hash and overwrite the global `var.image` value. We could bring this back, it is only a matter of looking if the key `image` is defined in the instance hash, if it is, we use the value as the instance image value, otherwise, we use the global `var.image` value.

So in GCP, line 73 
https://github.com/ComputeCanada/magic_castle/blob/11.7/gcp/infrastructure.tf#L73
would become:
``` image = lookup(each.value, "image", var.image)```

Documenting the feature properly will probably take more time than implementing it.

**Comment by cmd-ntrf** [comment]
PR #203 fixes this. Could you give it a try with Azure?
