### ISSUE TITLE
Question over AWS volume performance

### ISSUE THREAD

**Issue by verdurin** [ComputeCanada/magic_castle#71]
We have found in testing bioinformatics workloads on AWS with the default `gp2` that the performance using the EBS volume as the NFS backend is rather poor. In particular interactive response on the login node is bad when there is significant activity on the `/project` mount.

We would like to be able to use multiple `gp2` devices for greater throughput and IOPS, as is recommended in the AWS documentation. Admittedly this is an interim measure before support for Lustre is added.

Also not sure why LVM thin provisioned volumes are being used, and whether they are implicated in the performance bottleneck.

Certainly we will do more tests with different machine types but I wondered if you had seen any behaviour like this in your workshops.

**Comment by cmd-ntrf** [comment]
> performance using the EBS volume as the NFS backend is rather poor. In particular interactive response on the login node is bad when there is significant activity on the /project mount.

Before anything else, I must say that I'm glad that you're pushing boundaries of Magic Castle, and you are currently exploring uncharted territories. Most of our workshops, if not all, do not significantly use the filesystem, we did therefore rarely observed any performance issue for now.

MC is in dire need of some I/O performance testing that will guide future changes related to the infrastructure design. My main focus thus far has been to replicate the user experience from a software point of view, voluntarily neglecting performance. It might be time to change that, and gather a set of performance tests that should be run before releasing to make sure new changes do not impact the performance negatively.

Usage of LVM to provision the volumes is yet released. In 6.x and earlier, volumes were mounted directly on `mgmt1`, formated as xfs and exported with NFS. Was the poor performance of `/project` observed with `master` branch or a release?

LVM volumes are thin provisioned to allow eventual expansion of the storage and avoid errors when creating the volumes because a few megabytes dedicated to metadata are missing from the expected volume size set in the Terraform module. I do not expect this to be causing performance issue, but we definitively need testing. Using LVM provides us the ability to define pool of disks, to it would be possible to use multiple devices instead of a single one as it was the case in 6.x. The current configuration of home, project and scratch sharing the same pool is maybe not ideal for performance. Combining the disks in a common pool simplified the process of identifying which block devices corresponds to which partition.

**Comment by cmd-ntrf** [comment]
For AWS specifically, it might be worth looking at EFS as a replacement for our homemade NFS solution:
https://aws.amazon.com/efs/?nc1=h_ls
